const url = "https://handcraftb.onrender.com"
export default {
   USER_SIGNIN: url+"/customer/signin",
   USER_SIGNUP: url+"/customer/signup",
   VIEW_ALL_PRODUCT: url+"/product/viewproduct",
   SERACH_FILTER: url+"/product/search/",
   PRODUCT_BY_CATEGORY: url+"/product/products/",
   PRODUCT_BY_HOME_CATEGORY: url+"/product/products/",
   REMOVE_FROM_CART: url+"/cart/deleteproduct",
   VIEW_CART_ITEMS: url+"/cart/viewCartItems",
   ADD_TO_CART: url+"/cart/add-to-cart",
   PRODUCT_ADD: url+"/product/save",
   CUSTOMER_SAVE: url+"/customer/save",
   SELLER_SIGNIN: url+"/seller/signin",
   SELLER_SIGNUP: url+"/seller/signup",
   PRODUCT_LIST_BY_SELLER: url+"/product/productList",
   ORDER_BY_SELLER: url+"/order/getorderbyseller",
   UPDATE_PRODUCT: url+"/product/updated",
   VIEW_ALL_PRODUCT_ON_SCROLL: url+"/product/limitLoadproduct",
   CUSTOMER_SIGNIN: url+"/customer/customerSignin",
   VIEW_PRODUCT_BY_ID: url+"/product/",
   FETCH_CATEGORY: url+"/category/category-list",
   FETCH_FEATUREPRODUCT: url+"/product/featuresproduct",
   ADD_WISHLIST: url+"/wishlist/addtowishlist",
   VIEW_WISHLIST: url+"/wishlist/viewwishlist"
}
